### ISSUE TITLE
Hapi17 Compatibility

### ISSUE THREAD

**Issue by bastoune** [Salesflare/hapi-csv#33]
When I try to use it with Hapi v17 it doesn't work ...
`[1] "name" is required`

when 

`await mushApiV3.server.register({plugin: require('hapi-csv')})`

OR 

`[1] "register" must be a Function`

when

`await mushApiV3.server.register({register: require('hapi-csv')})`

**Comment by AdriVanHoudt** [comment]
Atm this is made for hapi 16 which is the version we're on.
I think we can accept a PR for 17 which I can release under a different npm tag or something. e.g. hapi-csv@hapi17

**Comment by AdriVanHoudt** [comment]
There is a PR for this https://github.com/Salesflare/hapi-csv/pull/34
