### ISSUE TITLE
Values need to escape double quotes

### ISSUE THREAD

**Issue by ckknight** [Salesflare/hapi-csv#9]
If you have a string like `'I said, "Hello"'`, that should be escaped in CSV as `"I said, ""Hello"""`, which it current is not.

Granted, there is some inconsistency as some exporters would produce `"I said, \"Hello\""`.

**Comment by AdriVanHoudt** [comment]
Thanks for reporting this. I checked wikipedia if this is indeed the case and either are correct. I currently do not have time to implement this but I am very open for a PR that adds an option to decide the way of escaping!
